### ISSUE TITLE
searchmulti crashes on extra (or missing?) columns

### ISSUE THREAD

**Issue by gjost** [denshoproject/namesdb-editor#16]
```
442-creators-results.csv
(names) ddr@kyuzo:/opt/namesdb-editor$ namesdb searchmulti /home/ddr/ddr-densho-442-person.csv --sql > /home/ddr/ddr-densho-44
2-persons-results.csv
Traceback (most recent call last):
  File "/opt/namesdb-editor/venv/names/bin/namesdb", line 33, in <module>
    sys.exit(load_entry_point('namesdb-editor==0.1.0', 'console_scripts', 'namesdb')())
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/namesdb_editor-0.1.0-py3.9.egg/names/cli.py", line 485, in searchmulti
    for row in batch.search_multi(csvfile, method):
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/namesdb_editor-0.1.0-py3.9.egg/names/batch.py", line 28, in search_multi
    oid,fieldname,names = row
ValueError: too many values to unpack (expected 3)
```

**Comment by gjost** [comment]
This line
```
"ddr-densho-442-116","persons","namepart: Yamato, Richard ""Dick""; namepart: Okubo, Donna"
```
is getting parsed as
```
['ddr-densho-442-116', 'persons', 'namepart: Yamato, Richard "Dick""; namepart: Okubo', ' Donna"']
```
where the final ` Donna"` is a separate list item.

**Comment by gjost** [comment]
I suspect the problem is that `names.batch.search_multi` is reading a slightly different dialect from what `ddrexport fieldcsv` is producing.

**Comment by gjost** [comment]
Fixed in `namesdb-editor` `develop` branch commit `bbab3a0` and pushed to `kyuzo`.
