### ISSUE TITLE
`'NoneType' object has no attribute 'facility_id'` exception when attempting to edit Person record

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#41]
When attempting to make a change to the `postexclusion_residence_state` field for the Person `88922_/nr010p642`, the names editor throws the exception: `'NoneType' object has no attribute 'facility_id'`

I was able to edit another Person record successfully just prior to encountering this error. (see: http://namesdbeditor.local/admin/names/revision/1966334/change/)

URL:
http://namesdbeditor.local/admin/names/person/88922_2Fnr010p642/change/?_changelist_filters=postexclusion_residence_state%3DNE%2BA.R.%2B6157133

Traceback:
```
Environment:


Request Method: POST
Request URL: http://namesdbeditor.local/admin/names/person/88922_2Fnr010p642/change/?_changelist_filters=postexclusion_residence_state%3DNE%2BA.R.%2B6157133

Django Version: 4.1.11
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'bootstrap_pagination',
 'drf_yasg',
 'rest_framework',
 'editor',
 'names',
 'namesdb_public']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1894, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1751, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1802, in _changeform_view
    if all_valid(formsets) and form_validated:
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/formsets.py", line 576, in all_valid
    return all([formset.is_valid() for formset in formsets])
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/formsets.py", line 576, in <listcomp>
    return all([formset.is_valid() for formset in formsets])
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/formsets.py", line 383, in is_valid
    self.errors
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/formsets.py", line 365, in errors
    self.full_clean()
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/formsets.py", line 428, in full_clean
    form_errors = form.errors
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/forms.py", line 200, in errors
    self.full_clean()
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/forms.py", line 437, in full_clean
    self._clean_fields()
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/forms.py", line 449, in _clean_fields
    value = field.clean(value)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/fields.py", line 199, in clean
    self.validate(value)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/models.py", line 1554, in validate
    return Field.validate(self, value)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/forms/fields.py", line 176, in validate
    if value in self.empty_values and self.required:
  File "/opt/namesdb-editor/src/names/models.py", line 90, in __eq__
    other_id = other.facility_id.split('-'); other_id[0] = int(other_id[0])

Exception Type: AttributeError at /admin/names/person/88922_2Fnr010p642/change/
Exception Value: 'NoneType' object has no attribute 'facility_id'
```

**Comment by gjost** [comment]
Fixed in `develop` branch commit `0a7a969` and pushed to `kyuzo`.

Problem was `Facility` and `Location.__eq__` functions did not support being compared with `None`
