### ISSUE TITLE
Can't delete Person record from admin webui: "FOREIGN KEY constraint failed"

### ISSUE THREAD

**Issue by GeoffFroh** [denshoproject/namesdb-editor#48]
When trying to delete a person record (http://namesdbeditor.local/admin/names/person/88922_2Fnr007dm1f/delete/), I get a "FOREIGN KEY constraint failed" error message (see full text below). The person is 
Toshiro James Tanaka (88922/nr007dm1f) (http://namesdbeditor.local/admin/names/person/88922_2Fnr007dm1f). There are no WRA26 or FAR records linked to the person record, and I manually removed all related revision records. 

(Note that the reason for deleting this record is that it is a duplicate. The real record is: "Toshiro James Tanaka (88922/nr007dm24)"; it should not be removed.)

FWIW, I have been able to delete person records in the past -- perhaps, December?

Traceback:
```
Environment:


Request Method: POST
Request URL: http://namesdbeditor.local/admin/names/person/88922_2Fnr007dm1f/delete/

Django Version: 4.1.13
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'bootstrap_pagination',
 'drf_yasg',
 'rest_framework',
 'editor',
 'names',
 'namesdb_public']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()

The above exception (FOREIGN KEY constraint failed) was the direct cause of the following exception:
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 2110, in delete_view
    return self._delete_view(request, object_id, extra_context)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/db/transaction.py", line 262, in __exit__
    connection.commit()
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/db/backends/base/base.py", line 330, in commit
    self._commit()
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/db/backends/base/base.py", line 306, in _commit
    return self.connection.commit()

Exception Type: IntegrityError at /admin/names/person/88922_2Fnr007dm1f/delete/
Exception Value: FOREIGN KEY constraint failed
```

**Comment by GeoffFroh** [comment]
I think I may have figured it out -- the `person_id` is still referenced in the `names_personfacility` table; but we removed access to it from the admin ui since it overlapped/was-replaced-by the `names_personlocation` table.

We had deferred the discussion about when/whether to get rid of the `names_personfacility` data completely -- we'll have to figure that out before this can be fully resolved. I'm adding an `enhancement` tag.

**Comment by GeoffFroh** [comment]
Because the `names_personfacility` data is redundant (it exists, or will exist, in `names_personlocation`, we can remove that table from the models. Before doing so, please dump the contents to csv, @gjost 

Thanks!

**Comment by gjost** [comment]
Wrote a quick script to dump the data to a CSV file:
```
from pathlib import Path
from names import fileio, models
from namesdb_public.models import FIELDS_PERSONFACILITY
csvfile = Path('/tmp/20240207_personfacilities.csv')
with csvfile.open('w') as f:
    writer = fileio.csv_writer(f)
    writer.writerow(FIELDS_PERSONFACILITY)
    for pf in models.PersonFacility.objects.all():
        result = writer.writerow(pf.dict().values())
```
File was moved to `/opt/namesdb-editor/20240207_personfacilities.csv` and then all `namesdb_personfacility` records were deleted from the database.

**Comment by GeoffFroh** [comment]
Reopened so we can test more. `Person` and `Facility` are many-to-many linked through `PersonFacility`, so there may be additional code to remove before closing.

**Comment by gjost** [comment]
I removed the `PersonFacility` class but that does not appear to have solved the problem.

It looks like the `IntegrityError` is because of our foreign key settings, specifically for what to do with records that link to a `Person` via a foreign key.  For example, in `FarRecord` there is this:
```
person = models.ForeignKey(Person, on_delete=models.DO_NOTHING, blank=True, null=True)
```
This protects `FarRecords` from being deleted when a `Person` is deleted, but it appears to still set off the `IntegrityError`.  `on_delete=models.SET_NULL` appears to work.

It's obvious what to do for `FarRecord` and `WraRecord`.  I think we want `PersonLocations` to get deleted when the `Person` is deleted.
