### ISSUE TITLE
Could not connect to ddr-idservice during `person-add`

### ISSUE THREAD

**Issue by gjost** [denshoproject/namesdb-editor#49]
`namesdb-editor` running on `kyuzo` could not connect to local `ddridservice` instance, also running on `kyuzo`, when trying to add a new `Person`.

**Comment by gjost** [comment]
```
Environment:

Request Method: POST
Request URL: http://namesdbeditor.local/admin/names/person/add/

Django Version: 4.1.13
Python Version: 3.9.2
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'bootstrap_pagination',
 'drf_yasg',
 'rest_framework',
 'editor',
 'names',
 'namesdb_public',
 'ireizo_public']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)

The above exception (timed out) was the direct cause of the following exception:
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 268, in handle_request
    raise exc
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 251, in handle_request
    response = connection.handle_request(request)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
    return self._connection.handle_request(request)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
    raise exc
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
    data = self._network_stream.read(
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc

The above exception (timed out) was the direct cause of the following exception:
  File "/opt/namesdb-editor/src/names/models.py", line 497, in _get_noid
    return noidminter.get_noids()[0]
  File "/opt/namesdb-editor/src/names/noidminter.py", line 8, in get_noids
    r = httpx.post(
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_api.py", line 317, in post
    return request(
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_api.py", line 104, in request
    return client.request(
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc

During handling of the above exception (timed out), another exception occurred:
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1891, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1751, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1803, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/namesdb-editor/src/names/admin.py", line 594, in save_model
    super().save_model(request, obj, form, change)
  File "/opt/namesdb-editor/venv/names/lib/python3.9/site-packages/django/contrib/admin/options.py", line 1226, in save_model
    obj.save()
  File "/opt/namesdb-editor/src/names/models.py", line 462, in save
    self.nr_id = self._get_noid()
  File "/opt/namesdb-editor/src/names/models.py", line 499, in _get_noid
    raise Exception(

Exception Type: Exception at /admin/names/person/add/
Exception Value: Could not connect to ddr-idservice at http://10.0.1.127:8082/noid/api/1.0/nr.zeedeedk/. Please check settings.
```

**Comment by GeoffFroh** [comment]
The above exception was generated on `kyuzo`; but accessed via Tailscale connection. Tailscale was v1.58.2 MacOS, updated 2 weeks ago

**Comment by gjost** [comment]
I can connect to `ddr-idservice` from `kyuzo` using `lynx`: `lynx http://10.0.1.127:8082/`, as can @GeoffFroh

**Comment by gjost** [comment]
And this just worked the way it was supposed to, on `kyuzo`:
```
(names) ddr@kyuzo:/opt/namesdb-editor$ make shell
source /opt/namesdb-editor/venv/names/bin/activate; \
python src/manage.py shell
>>> from names import csvfile,fileio,noidminter
>>> noidminter.get_noids()[0]
'88922/nr0160915'
```

**Comment by gjost** [comment]
Maybe it's an intermittent thing?
